# Generated by Django 4.2.19 on 2025-02-23 17:09

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                (
                    'date',
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date.today
                            )
                        ]
                    ),
                ),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
