# Generated by Django 4.2.19 on 2025-02-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'weekday',
                    models.IntegerField(
                        choices=[
                            (0, 'Monday'),
                            (1, 'Tuesday'),
                            (2, 'Wednesday'),
                            (3, 'Thursday'),
                            (4, 'Friday'),
                            (5, 'Saturday'),
                            (6, 'Sunday'),
                        ]
                    ),
                ),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                (
                    'worker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                (
                    'worker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
